import type { Metadata } from "next";
import { Inter, Cairo } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import MouseGlow from "@/components/MouseGlow";

const inter = Inter({ subsets: ["latin"] });
const cairo = Cairo({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cairo.className}>
        <main className="relative flex flex-col min-h-screen ">
          <Nav />
          <MouseGlow />
          <div className="flex-grow flex-1">{children}</div>
        </main>
      </body>
    </html>
  );
}
